export interface Municipality {
  region: string;
  regionalUnit: string;
  municipality: string;
}

export const MUNICIPALITIES: Municipality[] = [
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Ροδόπης", municipality: "Κομοτηνής" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Ροδόπης", municipality: "Αρριανών" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Ροδόπης", municipality: "Ιάσμου" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Ροδόπης", municipality: "Μαρωνείας – Σαπών" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Δράμας", municipality: "Δράμας" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Δράμας", municipality: "Δοξάτου" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Δράμας", municipality: "Κάτω Νευροκοπίου" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Δράμας", municipality: "Παρανεστίου" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Δράμας", municipality: "Προσοτσάνης" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Έβρου", municipality: "Αλεξανδρούπολης" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Έβρου", municipality: "Διδυμοτείχου" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Έβρου", municipality: "Ορεστιάδας" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Έβρου", municipality: "Σαμοθράκης" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Έβρου", municipality: "Σουφλίου" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Θάσου", municipality: "Θάσου" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Καβάλας", municipality: "Καβάλας" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Καβάλας", municipality: "Νέστου" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Καβάλας", municipality: "Παγγαίου" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Ξάνθης", municipality: "Ξάνθης" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Ξάνθης", municipality: "Αβδήρων" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Ξάνθης", municipality: "Μύκης" },
  { region: "Ανατολικής Μακεδονίας – Θράκης", regionalUnit: "Ξάνθης", municipality: "Τοπείρου" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Θεσσαλονίκης" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Αμπελοκήπων – Μενεμένης" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Βόλβης" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Δέλτα" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Θερμαϊκού" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Θέρμης" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Καλαμαριάς" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Κορδελιού – Ευόσμου" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Λαγκαδά" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Νεάπολης – Συκεών" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Παύλου Μελά" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Πυλαίας – Χορτιάτη" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Χαλκηδόνος" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Θεσσαλονίκης", municipality: "Ωραιοκάστρου" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Ημαθίας", municipality: "Βέροιας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Ημαθίας", municipality: "Αλεξάνδρειας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Ημαθίας", municipality: "Ηρωικής Πόλεως Νάουσας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Κιλκίς", municipality: "Κιλκίς" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Κιλκίς", municipality: "Παιονίας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Πέλλας", municipality: "Έδεσσας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Πέλλας", municipality: "Αλμωπίας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Πέλλας", municipality: "Πέλλας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Πέλλας", municipality: "Σκύδρας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Πιερίας", municipality: "Κατερίνης" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Πιερίας", municipality: "Δίου – Ολύμπου" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Πιερίας", municipality: "Πύδνας – Κολινδρού" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Σερρών", municipality: "Σερρών" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Σερρών", municipality: "Αμφίπολης" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Σερρών", municipality: "Βισαλτίας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Σερρών", municipality: "Εμμανουήλ Παππά" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Σερρών", municipality: "Ηράκλειας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Σερρών", municipality: "Νέας Ζίχνης" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Σερρών", municipality: "Σιντικής" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Χαλκιδικής", municipality: "Πολύγυρου" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Χαλκιδικής", municipality: "Αριστοτέλη" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Χαλκιδικής", municipality: "Κασσάνδρας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Χαλκιδικής", municipality: "Νέας Προποντίδας" },
  { region: "Κεντρικής Μακεδονίας", regionalUnit: "Χαλκιδικής", municipality: "Σιθωνίας" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Κοζάνης", municipality: "Κοζάνης" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Κοζάνης", municipality: "Βελβεντού" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Κοζάνης", municipality: "Βοΐου" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Κοζάνης", municipality: "Εορδαίας" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Κοζάνης", municipality: "Σερβίων" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Γρεβενών", municipality: "Γρεβενών" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Γρεβενών", municipality: "Δεσκάτης" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Καστοριάς", municipality: "Καστοριάς" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Καστοριάς", municipality: "Άργους Ορεστικού" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Καστοριάς", municipality: "Νεστόριου" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Φλώρινας", municipality: "Φλώρινας" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Φλώρινας", municipality: "Αμυνταίου" },
  { region: "Δυτικής Μακεδονίας", regionalUnit: "Φλώρινας", municipality: "Πρεσπών" },
  { region: "Ηπείρου", regionalUnit: "Ιωαννίνων", municipality: "Ιωαννιτών" },
  { region: "Ηπείρου", regionalUnit: "Ιωαννίνων", municipality: "Βορείων Τζουμέρκων" },
  { region: "Ηπείρου", regionalUnit: "Ιωαννίνων", municipality: "Δωδώνης" },
  { region: "Ηπείρου", regionalUnit: "Ιωαννίνων", municipality: "Ζαγορίου" },
  { region: "Ηπείρου", regionalUnit: "Ιωαννίνων", municipality: "Ζίτσας" },
  { region: "Ηπείρου", regionalUnit: "Ιωαννίνων", municipality: "Κόνιτσας" },
  { region: "Ηπείρου", regionalUnit: "Ιωαννίνων", municipality: "Μετσόβου" },
  { region: "Ηπείρου", regionalUnit: "Ιωαννίνων", municipality: "Πωγωνίου" },
  { region: "Ηπείρου", regionalUnit: "Άρτας", municipality: "Αρταίων" },
  { region: "Ηπείρου", regionalUnit: "Άρτας", municipality: "Γεωργίου Καραϊσκάκη" },
  { region: "Ηπείρου", regionalUnit: "Άρτας", municipality: "Κεντρικών Τζουμέρκων" },
  { region: "Ηπείρου", regionalUnit: "Άρτας", municipality: "Νικόλαου Σκουφά" },
  { region: "Ηπείρου", regionalUnit: "Θεσπρωτίας", municipality: "Ηγουμενίτσας" },
  { region: "Ηπείρου", regionalUnit: "Θεσπρωτίας", municipality: "Σουλίου" },
  { region: "Ηπείρου", regionalUnit: "Θεσπρωτίας", municipality: "Φιλιατών" },
  { region: "Ηπείρου", regionalUnit: "Πρέβεζας", municipality: "Πρέβεζας" },
  { region: "Ηπείρου", regionalUnit: "Πρέβεζας", municipality: "Ζηρού" },
  { region: "Ηπείρου", regionalUnit: "Πρέβεζας", municipality: "Πάργας" },
  { region: "Θεσσαλίας", regionalUnit: "Λάρισας", municipality: "Λαρισαίων" },
  { region: "Θεσσαλίας", regionalUnit: "Λάρισας", municipality: "Αγιάς" },
  { region: "Θεσσαλίας", regionalUnit: "Λάρισας", municipality: "Ελασσόνας" },
  { region: "Θεσσαλίας", regionalUnit: "Λάρισας", municipality: "Κιλελέρ" },
  { region: "Θεσσαλίας", regionalUnit: "Λάρισας", municipality: "Τεμπών" },
  { region: "Θεσσαλίας", regionalUnit: "Λάρισας", municipality: "Τυρνάβου" },
  { region: "Θεσσαλίας", regionalUnit: "Λάρισας", municipality: "Φαρσάλων" },
  { region: "Θεσσαλίας", regionalUnit: "Καρδίτσας", municipality: "Καρδίτσας" },
  { region: "Θεσσαλίας", regionalUnit: "Καρδίτσας", municipality: "Αργιθέας" },
  { region: "Θεσσαλίας", regionalUnit: "Καρδίτσας", municipality: "Λίμνης Πλαστήρα" },
  { region: "Θεσσαλίας", regionalUnit: "Καρδίτσας", municipality: "Μουζακίου" },
  { region: "Θεσσαλίας", regionalUnit: "Καρδίτσας", municipality: "Παλαμά" },
  { region: "Θεσσαλίας", regionalUnit: "Καρδίτσας", municipality: "Σοφάδων" },
  { region: "Θεσσαλίας", regionalUnit: "Μαγνησίας", municipality: "Βόλου" },
  { region: "Θεσσαλίας", regionalUnit: "Μαγνησίας", municipality: "Αλμυρού" },
  { region: "Θεσσαλίας", regionalUnit: "Μαγνησίας", municipality: "Ζαγοράς – Μουρεσίου" },
  { region: "Θεσσαλίας", regionalUnit: "Μαγνησίας", municipality: "Νοτίου Πηλίου" },
  { region: "Θεσσαλίας", regionalUnit: "Μαγνησίας", municipality: "Ρήγα Φεραίου" },
  { region: "Θεσσαλίας", regionalUnit: "Σποράδων", municipality: "Σκιάθου" },
  { region: "Θεσσαλίας", regionalUnit: "Σποράδων", municipality: "Αλοννήσου" },
  { region: "Θεσσαλίας", regionalUnit: "Σποράδων", municipality: "Σκοπέλου" },
  { region: "Θεσσαλίας", regionalUnit: "Τρικάλων", municipality: "Τρικκαίων" },
  { region: "Θεσσαλίας", regionalUnit: "Τρικάλων", municipality: "Μετεώρων" },
  { region: "Θεσσαλίας", regionalUnit: "Τρικάλων", municipality: "Πύλης" },
  { region: "Θεσσαλίας", regionalUnit: "Τρικάλων", municipality: "Φαρκαδόνας" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Φθιώτιδας", municipality: "Λαμιέων" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Φθιώτιδας", municipality: "Αμφίκλειας – Ελάτειας" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Φθιώτιδας", municipality: "Δομοκού" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Φθιώτιδας", municipality: "Καμένων Βούρλων" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Φθιώτιδας", municipality: "Λοκρών" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Φθιώτιδας", municipality: "Μακρακώμης" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Φθιώτιδας", municipality: "Στυλίδος" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Βοιωτίας", municipality: "Λεβαδέων" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Βοιωτίας", municipality: "Αλιάρτου – Θεσπιέων" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Βοιωτίας", municipality: "Διστόμου – Αράχοβας – Αντίκυρας" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Βοιωτίας", municipality: "Θηβαίων" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Βοιωτίας", municipality: "Ορχομενού" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Βοιωτίας", municipality: "Τανάγρας" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Εύβοιας", municipality: "Χαλκιδέων" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Εύβοιας", municipality: "Διρφύων – Μεσσαπίων" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Εύβοιας", municipality: "Ερέτριας" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Εύβοιας", municipality: "Ιστιαίας – Αιδηψού" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Εύβοιας", municipality: "Καρύστου" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Εύβοιας", municipality: "Κύμης – Αλιβερίου" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Εύβοιας", municipality: "Μαντουδίου – Λίμνης – Αγίας Άννας" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Εύβοιας", municipality: "Σκύρου" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Ευρυτανίας", municipality: "Καρπενησίου" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Ευρυτανίας", municipality: "Αγράφων" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Φωκίδας", municipality: "Δελφών" },
  { region: "Στερεάς Ελλάδας", regionalUnit: "Φωκίδας", municipality: "Δωρίδος" },
  { region: "Ιονίων Νήσων", regionalUnit: "Κέρκυρας", municipality: "Κεντρικής Κέρκυρας – Διαποντίων Νήσων" },
  { region: "Ιονίων Νήσων", regionalUnit: "Κέρκυρας", municipality: "Βόρειας Κέρκυρας" },
  { region: "Ιονίων Νήσων", regionalUnit: "Κέρκυρας", municipality: "Νότιας Κέρκυρας" },
  { region: "Ιονίων Νήσων", regionalUnit: "Κέρκυρας", municipality: "Παξών" },
  { region: "Ιονίων Νήσων", regionalUnit: "Ζακύνθου", municipality: "Ζακύνθου" },
  { region: "Ιονίων Νήσων", regionalUnit: "Ιθάκης", municipality: "Ιθάκης" },
  { region: "Ιονίων Νήσων", regionalUnit: "Κεφαλληνίας", municipality: "Αργοστολίου" },
  { region: "Ιονίων Νήσων", regionalUnit: "Κεφαλληνίας", municipality: "Ληξουρίου" },
  { region: "Ιονίων Νήσων", regionalUnit: "Κεφαλληνίας", municipality: "Σάμης" },
  { region: "Ιονίων Νήσων", regionalUnit: "Λευκάδας", municipality: "Λευκάδας" },
  { region: "Ιονίων Νήσων", regionalUnit: "Λευκάδας", municipality: "Μεγανησίου" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αχαΐας", municipality: "Πατρέων" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αχαΐας", municipality: "Αιγιαλείας" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αχαΐας", municipality: "Δυτικής Αχαΐας" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αχαΐας", municipality: "Ερυμάνθου" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αχαΐας", municipality: "Καλαβρύτων" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αιτωλίας – Ακαρνανίας", municipality: "Ιεράς Πόλης Μεσολογγίου" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αιτωλίας – Ακαρνανίας", municipality: "Αγρινίου" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αιτωλίας – Ακαρνανίας", municipality: "Ακτίου – Βόνιτσας" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αιτωλίας – Ακαρνανίας", municipality: "Αμφιλοχίας" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αιτωλίας – Ακαρνανίας", municipality: "Θέρμου" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αιτωλίας – Ακαρνανίας", municipality: "Ναυπακτίας" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Αιτωλίας – Ακαρνανίας", municipality: "Ξηρομέρου" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Ηλείας", municipality: "Πύργου" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Ηλείας", municipality: "Ανδραβίδας – Κυλλήνης" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Ηλείας", municipality: "Ανδρίτσαινας – Κρεστένων" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Ηλείας", municipality: "Αρχαίας Ολυμπίας" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Ηλείας", municipality: "Ζαχάρως" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Ηλείας", municipality: "Ήλιδας" },
  { region: "Δυτικής Ελλάδας", regionalUnit: "Ηλείας", municipality: "Πηνειού" },
  { region: "Πελοποννήσου", regionalUnit: "Αρκαδίας", municipality: "Τρίπολης" },
  { region: "Πελοποννήσου", regionalUnit: "Αρκαδίας", municipality: "Βόρειας Κυνουρίας" },
  { region: "Πελοποννήσου", regionalUnit: "Αρκαδίας", municipality: "Γορτυνίας" },
  { region: "Πελοποννήσου", regionalUnit: "Αρκαδίας", municipality: "Μεγαλόπολης" },
  { region: "Πελοποννήσου", regionalUnit: "Αρκαδίας", municipality: "Νότιας Κυνουρίας" },
  { region: "Πελοποννήσου", regionalUnit: "Αργολίδας", municipality: "Ναυπλιέων" },
  { region: "Πελοποννήσου", regionalUnit: "Αργολίδας", municipality: "Άργους – Μυκηνών" },
  { region: "Πελοποννήσου", regionalUnit: "Αργολίδας", municipality: "Επιδαύρου" },
  { region: "Πελοποννήσου", regionalUnit: "Αργολίδας", municipality: "Ερμιονίδας" },
  { region: "Πελοποννήσου", regionalUnit: "Κορινθίας", municipality: "Κορινθίων" },
  { region: "Πελοποννήσου", regionalUnit: "Κορινθίας", municipality: "Βέλου – Βόχας" },
  { region: "Πελοποννήσου", regionalUnit: "Κορινθίας", municipality: "Λουτρακίου – Περαχώρας – Αγίων Θεοδώρων" },
  { region: "Πελοποννήσου", regionalUnit: "Κορινθίας", municipality: "Νεμέας" },
  { region: "Πελοποννήσου", regionalUnit: "Κορινθίας", municipality: "Ξυλοκάστρου – Ευρωστίνης" },
  { region: "Πελοποννήσου", regionalUnit: "Κορινθίας", municipality: "Σικυωνίων" },
  { region: "Πελοποννήσου", regionalUnit: "Λακωνίας", municipality: "Σπάρτης" },
  { region: "Πελοποννήσου", regionalUnit: "Λακωνίας", municipality: "Ανατολικής Μάνης" },
  { region: "Πελοποννήσου", regionalUnit: "Λακωνίας", municipality: "Ελαφονήσου" },
  { region: "Πελοποννήσου", regionalUnit: "Λακωνίας", municipality: "Ευρώτα" },
  { region: "Πελοποννήσου", regionalUnit: "Λακωνίας", municipality: "Μονεμβασιάς" },
  { region: "Πελοποννήσου", regionalUnit: "Μεσσηνίας", municipality: "Καλαμάτας" },
  { region: "Πελοποννήσου", regionalUnit: "Μεσσηνίας", municipality: "Δυτικής Μάνης" },
  { region: "Πελοποννήσου", regionalUnit: "Μεσσηνίας", municipality: "Μεσσήνης" },
  { region: "Πελοποννήσου", regionalUnit: "Μεσσηνίας", municipality: "Οιχαλίας" },
  { region: "Πελοποννήσου", regionalUnit: "Μεσσηνίας", municipality: "Πύλου – Νέστορος" },
  { region: "Πελοποννήσου", regionalUnit: "Μεσσηνίας", municipality: "Τριφυλίας" },
  { region: "Αττικής", regionalUnit: "Κεντρικού Τομέα Αθηνών", municipality: "Αθηναίων" },
  { region: "Αττικής", regionalUnit: "Κεντρικού Τομέα Αθηνών", municipality: "Βύρωνος" },
  { region: "Αττικής", regionalUnit: "Κεντρικού Τομέα Αθηνών", municipality: "Γαλατσίου" },
  { region: "Αττικής", regionalUnit: "Κεντρικού Τομέα Αθηνών", municipality: "Δάφνης – Υμηττού" },
  { region: "Αττικής", regionalUnit: "Κεντρικού Τομέα Αθηνών", municipality: "Ζωγράφου" },
  { region: "Αττικής", regionalUnit: "Κεντρικού Τομέα Αθηνών", municipality: "Ηλιουπόλεως" },
  { region: "Αττικής", regionalUnit: "Κεντρικού Τομέα Αθηνών", municipality: "Καισαριανής" },
  { region: "Αττικής", regionalUnit: "Κεντρικού Τομέα Αθηνών", municipality: "Νέας Φιλαδέλφειας – Νέας Χαλκηδόνος" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Αμαρουσίου" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Αγίας Παρασκευής" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Βριλησσίων" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Ηρακλείου" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Κηφισιάς" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Λυκόβρυσης – Πεύκης" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Μεταμορφώσεως" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Νέας Ιωνίας" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Παπάγου – Χολαργού" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Πεντέλης" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Φιλοθέης – Ψυχικού" },
  { region: "Αττικής", regionalUnit: "Βορείου Τομέα Αθηνών", municipality: "Χαλανδρίου" },
  { region: "Αττικής", regionalUnit: "Δυτικού Τομέα Αθηνών", municipality: "Περιστερίου" },
  { region: "Αττικής", regionalUnit: "Δυτικού Τομέα Αθηνών", municipality: "Αγίας Βαρβάρας" },
  { region: "Αττικής", regionalUnit: "Δυτικού Τομέα Αθηνών", municipality: "Αγίων Αναργύρων – Καματερού" },
  { region: "Αττικής", regionalUnit: "Δυτικού Τομέα Αθηνών", municipality: "Αιγάλεω" },
  { region: "Αττικής", regionalUnit: "Δυτικού Τομέα Αθηνών", municipality: "Ιλίου" },
  { region: "Αττικής", regionalUnit: "Δυτικού Τομέα Αθηνών", municipality: "Πετρουπόλεως" },
  { region: "Αττικής", regionalUnit: "Δυτικού Τομέα Αθηνών", municipality: "Χαϊδαρίου" },
  { region: "Αττικής", regionalUnit: "Νοτίου Τομέα Αθηνών", municipality: "Καλλιθέας" },
  { region: "Αττικής", regionalUnit: "Νοτίου Τομέα Αθηνών", municipality: "Αγίου Δημητρίου" },
  { region: "Αττικής", regionalUnit: "Νοτίου Τομέα Αθηνών", municipality: "Αλίμου" },
  { region: "Αττικής", regionalUnit: "Νοτίου Τομέα Αθηνών", municipality: "Γλυφάδας" },
  { region: "Αττικής", regionalUnit: "Νοτίου Τομέα Αθηνών", municipality: "Ελληνικού – Αργυρούπολης" },
  { region: "Αττικής", regionalUnit: "Νοτίου Τομέα Αθηνών", municipality: "Μοσχάτου – Ταύρου" },
  { region: "Αττικής", regionalUnit: "Νοτίου Τομέα Αθηνών", municipality: "Νέας Σμύρνης" },
  { region: "Αττικής", regionalUnit: "Νοτίου Τομέα Αθηνών", municipality: "Παλαιού Φαλήρου" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Αχαρνών" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Βάρης – Βούλας – Βουλιαγμένης" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Διονύσου" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Κρωπίας" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Λαυρεωτικής" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Μαραθώνος" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Μαρκόπουλου Μεσογαίας" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Παιανίας" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Παλλήνης" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Ραφήνας – Πικερμίου" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Σαρωνικού" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Σπάτων – Αρτέμιδος" },
  { region: "Αττικής", regionalUnit: "Ανατολικής Αττικής", municipality: "Ωρωπού" },
  { region: "Αττικής", regionalUnit: "Δυτικής Αττικής", municipality: "Ελευσίνας" },
  { region: "Αττικής", regionalUnit: "Δυτικής Αττικής", municipality: "Ασπροπύργου" },
  { region: "Αττικής", regionalUnit: "Δυτικής Αττικής", municipality: "Μάνδρας – Ειδυλλίας" },
  { region: "Αττικής", regionalUnit: "Δυτικής Αττικής", municipality: "Μεγαρέων" },
  { region: "Αττικής", regionalUnit: "Δυτικής Αττικής", municipality: "Φυλής" },
  { region: "Αττικής", regionalUnit: "Πειραιώς", municipality: "Πειραιώς" },
  { region: "Αττικής", regionalUnit: "Πειραιώς", municipality: "Κερατσινίου – Δραπετσώνας" },
  { region: "Αττικής", regionalUnit: "Πειραιώς", municipality: "Κορυδαλλού" },
  { region: "Αττικής", regionalUnit: "Πειραιώς", municipality: "Νίκαιας – Αγίου Ιωάννη Ρέντη" },
  { region: "Αττικής", regionalUnit: "Πειραιώς", municipality: "Περάματος" },
  { region: "Αττικής", regionalUnit: "Νήσων", municipality: "Σαλαμίνος" },
  { region: "Αττικής", regionalUnit: "Νήσων", municipality: "Αγκιστρίου" },
  { region: "Αττικής", regionalUnit: "Νήσων", municipality: "Αίγινας" },
  { region: "Αττικής", regionalUnit: "Νήσων", municipality: "Κυθήρων" },
  { region: "Αττικής", regionalUnit: "Νήσων", municipality: "Πόρου" },
  { region: "Αττικής", regionalUnit: "Νήσων", municipality: "Σπετσών" },
  { region: "Αττικής", regionalUnit: "Νήσων", municipality: "Τροιζηνίας – Μεθάνων" },
  { region: "Αττικής", regionalUnit: "Νήσων", municipality: "Ύδρας" },
  { region: "Βορείου Αιγαίου", regionalUnit: "Λέσβου", municipality: "Μυτιλήνης" },
  { region: "Βορείου Αιγαίου", regionalUnit: "Λέσβου", municipality: "Δυτικής Λέσβου" },
  { region: "Βορείου Αιγαίου", regionalUnit: "Ικαρίας", municipality: "Ικαρίας" },
  { region: "Βορείου Αιγαίου", regionalUnit: "Ικαρίας", municipality: "Φούρνων Κορσεών" },
  { region: "Βορείου Αιγαίου", regionalUnit: "Λήμνου", municipality: "Λήμνου" },
  { region: "Βορείου Αιγαίου", regionalUnit: "Λήμνου", municipality: "Αγίου Ευστρατίου" },
  { region: "Βορείου Αιγαίου", regionalUnit: "Σάμου", municipality: "Ανατολικής Σάμου" },
  { region: "Βορείου Αιγαίου", regionalUnit: "Σάμου", municipality: "Δυτικής Σάμου" },
  { region: "Βορείου Αιγαίου", regionalUnit: "Χίου", municipality: "Χίου" },
  { region: "Βορείου Αιγαίου", regionalUnit: "Χίου", municipality: "Ηρωικής Νήσου Ψαρών" },
  { region: "Βορείου Αιγαίου", regionalUnit: "Χίου", municipality: "Οινουσσών" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Σύρου", municipality: "Σύρου – Ερμούπολης" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Άνδρου", municipality: "Άνδρου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Θήρας", municipality: "Θήρας" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Θήρας", municipality: "Ανάφης" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Θήρας", municipality: "Ιητών" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Θήρας", municipality: "Σικίνου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Θήρας", municipality: "Φολεγάνδρου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Καλύμνου", municipality: "Καλυμνίων" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Καλύμνου", municipality: "Αγαθονησίου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Καλύμνου", municipality: "Αστυπάλαιας" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Καλύμνου", municipality: "Λειψών" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Καλύμνου", municipality: "Λέρου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Καλύμνου", municipality: "Πάτμου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Καρπάθου – Ηρωικής Νήσου Κάσου", municipality: "Καρπάθου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Καρπάθου – Ηρωικής Νήσου Κάσου", municipality: "Ηρωικής Νήσου Κάσου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Κέας – Κύθνου", municipality: "Κέας" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Κέας – Κύθνου", municipality: "Κύθνου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Κω", municipality: "Κω" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Κω", municipality: "Νισύρου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Μήλου", municipality: "Μήλου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Μήλου", municipality: "Κιμώλου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Μήλου", municipality: "Σερίφου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Μήλου", municipality: "Σίφνου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Μυκόνου", municipality: "Μυκόνου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Νάξου", municipality: "Αμοργού" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Νάξου", municipality: "Νάξου – Μικρών Κυκλάδων" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Πάρου", municipality: "Πάρου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Πάρου", municipality: "Αντιπάρου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Ρόδου", municipality: "Ρόδου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Ρόδου", municipality: "Μεγίστης" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Ρόδου", municipality: "Σύμης" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Ρόδου", municipality: "Τήλου" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Ρόδου", municipality: "Χάλκης" },
  { region: "Νοτίου Αιγαίου", regionalUnit: "Τήνου", municipality: "Τήνου" },
  { region: "Κρήτης", regionalUnit: "Ηρακλείου", municipality: "Ηρακλείου" },
  { region: "Κρήτης", regionalUnit: "Ηρακλείου", municipality: "Αρχανών – Αστερουσίων" },
  { region: "Κρήτης", regionalUnit: "Ηρακλείου", municipality: "Βιάννου" },
  { region: "Κρήτης", regionalUnit: "Ηρακλείου", municipality: "Γόρτυνας" },
  { region: "Κρήτης", regionalUnit: "Ηρακλείου", municipality: "Μαλεβιζίου" },
  { region: "Κρήτης", regionalUnit: "Ηρακλείου", municipality: "Μινώα Πεδιάδας" },
  { region: "Κρήτης", regionalUnit: "Ηρακλείου", municipality: "Φαιστού" },
  { region: "Κρήτης", regionalUnit: "Ηρακλείου", municipality: "Χερσονήσου" },
  { region: "Κρήτης", regionalUnit: "Λασιθίου", municipality: "Αγίου Νικολάου" },
  { region: "Κρήτης", regionalUnit: "Λασιθίου", municipality: "Ιεράπετρας" },
  { region: "Κρήτης", regionalUnit: "Λασιθίου", municipality: "Οροπεδίου Λασιθίου" },
  { region: "Κρήτης", regionalUnit: "Λασιθίου", municipality: "Σητείας" },
  { region: "Κρήτης", regionalUnit: "Ρεθύμνου", municipality: "Ρεθύμνης" },
  { region: "Κρήτης", regionalUnit: "Ρεθύμνου", municipality: "Αγίου Βασιλείου" },
  { region: "Κρήτης", regionalUnit: "Ρεθύμνου", municipality: "Αμαρίου" },
  { region: "Κρήτης", regionalUnit: "Ρεθύμνου", municipality: "Ανωγείων" },
  { region: "Κρήτης", regionalUnit: "Ρεθύμνου", municipality: "Μυλοποτάμου" },
  { region: "Κρήτης", regionalUnit: "Χανίων", municipality: "Χανίων" },
  { region: "Κρήτης", regionalUnit: "Χανίων", municipality: "Αποκορώνου" },
  { region: "Κρήτης", regionalUnit: "Χανίων", municipality: "Γαύδου" },
  { region: "Κρήτης", regionalUnit: "Χανίων", municipality: "Καντάνου – Σελίνου" },
  { region: "Κρήτης", regionalUnit: "Χανίων", municipality: "Κισσάμου" },
  { region: "Κρήτης", regionalUnit: "Χανίων", municipality: "Πλατανιά" },
  { region: "Κρήτης", regionalUnit: "Χανίων", municipality: "Σφακίων" }
];

export function getAllMunicipalities(): Municipality[] {
  return MUNICIPALITIES;
}

export function searchMunicipalities(query: string): Municipality[] {
  const searchTerm = query.toLowerCase().trim();
  
  if (!searchTerm) return MUNICIPALITIES;

  return MUNICIPALITIES.filter(m => 
    m.municipality.toLowerCase().includes(searchTerm) ||
    m.regionalUnit.toLowerCase().includes(searchTerm) ||
    m.region.toLowerCase().includes(searchTerm)
  );
}